const express = require('express');
const app = express();
const router = express.Router();
const index = require('./routes/index');
const personRoute = require('./routes/personRoute');
const restaurantRoute = require('./routes/restaurantRoute');
app.use('/', index);
app.use('/persons', personRoute);
app.use('/restaurant', restaurantRoute);
module.exports = app;